[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace]
members = ["app", "ui"]

[workspace.dependencies]
bevy = {version = "0.13.0", features = ["dynamic_linking"]}
bevy-inspector-egui = "0.24.0"
rand = "0.8.5"

